[package]
name = "argent"
version = "0.1.0"
cairo-version = "2.7.0-rc.3"

[[target.starknet-contract]]
sierra = true
casm = true
allowed-libfuncs-list.name = "audited"
build-external-contracts = ["openzeppelin::presets::account::AccountUpgradeable"]

# TODO Revert once alexandria is merged
[dependencies]
starknet = "2.7.0-rc.3"
alexandria_math = { git = "https://github.com/gaetbout/quaireaux.git", rev = "a0b724cdfdb004c2669b5058bcef01e99bf9ebeb" }
alexandria_encoding = { git = "https://github.com/gaetbout/quaireaux.git", rev = "a0b724cdfdb004c2669b5058bcef01e99bf9ebeb" }
alexandria_merkle_tree = { git = "https://github.com/gaetbout/quaireaux.git", rev="a0b724cdfdb004c2669b5058bcef01e99bf9ebeb" }
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.27.0" }
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", rev = "5f03fba338b4cb321776947fb98b4584a32adece" }

[tool.fmt]
max-line-length = 120
sort-module-level-items = true

[scripts]
test = "snforge test"
format = "scarb fmt && yarn prettier --write ."
lint = "yarn eslint ."
test-ts = "scarb --profile release build && yarn tsc && yarn mocha tests-integration/*.test.ts"
test-multisig = "scarb --profile release build && yarn tsc && yarn mocha tests-integration/multisig*.test.ts"
test-session = "scarb --profile release build && yarn tsc && yarn mocha tests-integration/session*.test.ts"
test-list = "scarb --profile release build && yarn tsc && yarn mocha --dry-run tests-integration/*.test.ts"
start-devnet = "./scripts/start-devnet.sh"
kill-devnet = "lsof -t -i tcp:5050 | xargs kill"
profile = "scarb --profile release build && node --loader ts-node/esm scripts/profile-account.ts"
deploy-account = "scarb --profile release build && node --loader ts-node/esm scripts/deploy-account.ts"
deploy-multisig = "scarb --profile release build && node --loader ts-node/esm scripts/deploy-multisig.ts"
generate-signature = "node --loader ts-node/esm ./scripts/generate-signature.ts"
update-webauthn-dapp = "scarb --profile release build && cp target/release/*ArgentAccount* examples/webauthn/src/lib"