[package]
name = "argent"
version = "0.1.0"
cairo-version = "2.9.2"
edition="2024_07"

[[target.starknet-contract]]
sierra = true
casm = true
allowed-libfuncs-list.name = "audited"
build-external-contracts = ["openzeppelin_presets::account::AccountUpgradeable"]

# Uses packages form scarbs.xyz
[dependencies]
starknet = "2.9.2"
assert_macros = "2.9.2"
snforge_std = "0.36.0"
alexandria_encoding = { git = "https://github.com/keep-starknet-strange/alexandria.git", rev = "162bed1" }
alexandria_merkle_tree = { git = "https://github.com/keep-starknet-strange/alexandria.git", rev="162bed1" }
openzeppelin_security = "0.20.0"
openzeppelin_presets = "0.20.0"

[tool.fmt]
max-line-length = 120
sort-module-level-items = true

[scripts]
test = "snforge test"
format = "scarb fmt && yarn prettier --write ."
lint = "yarn eslint ."
test-ts = "scarb --profile release build && yarn tsc && yarn mocha --recursive tests-integration/ --extension .test.ts"
test-ts-sc = "yarn tsc && yarn mocha --recursive tests-integration/ --extension .test.ts"
test-multisig = "scarb --profile release build && yarn tsc && yarn mocha tests-integration/multisig*.test.ts"
test-session = "scarb --profile release build && yarn tsc && yarn mocha tests-integration/session/*.test.ts"
test-multiowner = "scarb --profile release build && yarn tsc && yarn mocha tests-integration/multiowner/*.test.ts"
test-list = "scarb --profile release build && yarn tsc && yarn mocha --dry-run tests-integration/*.test.ts"
start-devnet = "docker build -t devnet . && docker run -d -p 127.0.0.1:5050:5050 devnet"
kill-devnet = "docker ps -q --filter 'ancestor=devnet' | xargs docker stop"
profile = "scarb --profile release build && node --loader ts-node/esm scripts/profile-account.ts"
deploy-account = "scarb --profile release build && node --loader ts-node/esm scripts/deploy-account.ts"
deploy-multisig = "scarb --profile release build && node --loader ts-node/esm scripts/deploy-multisig.ts"
generate-signature = "node --loader ts-node/esm ./scripts/generate-signature.ts"
update-webauthn-dapp = "scarb --profile release build && cp target/release/*_ArgentAccount* examples/webauthn/src/lib && scarb run format"
print-contract-size = "scarb --profile release build && node --loader ts-node/esm ./scripts/print-contract-size.ts"

# Allows to use the repository as dependency in other projects
[lib]
