[package]
name = "argent"
version = "0.1.0"
cairo-version = "2.10.0-rc.1"
edition="2023_01"

[[target.starknet-contract]]
sierra = true
casm = true
allowed-libfuncs-list.name = "audited"
build-external-contracts = ["openzeppelin_presets::account::AccountUpgradeable"]

# Uses packages form scarbs.xyz
[dependencies]
starknet = "2.10.0-rc.1"
assert_macros = "2.10.0-rc.1"
snforge_std = "0.36.0"
# TODO Change when they release 
alexandria_math = { git = "https://github.com/gaetbout/quaireaux.git", rev = "0f5a47b" }
alexandria_encoding = { git = "https://github.com/gaetbout/quaireaux.git", rev = "0f5a47b" }
alexandria_merkle_tree = { git = "https://github.com/gaetbout/quaireaux.git", rev="0f5a47b" }
openzeppelin_security = { git = "https://github.com/gaetbout/cairo-contracts", rev="9ac1411" }
openzeppelin_presets = { git = "https://github.com/gaetbout/cairo-contracts", rev="9ac1411" }

[tool.fmt]
max-line-length = 120
sort-module-level-items = true

[scripts]
test = "snforge test"
format = "scarb fmt && yarn prettier --write ."
lint = "yarn eslint ."
test-ts = "scarb --profile release build && yarn tsc && yarn mocha --recursive tests-integration/ --extension .test.ts"
test-ts-sc = "yarn tsc && yarn mocha --recursive tests-integration/ --extension .test.ts"
test-multisig = "scarb --profile release build && yarn tsc && yarn mocha tests-integration/multisig*.test.ts"
test-session = "scarb --profile release build && yarn tsc && yarn mocha tests-integration/session/*.test.ts"
test-multiowner = "scarb --profile release build && yarn tsc && yarn mocha tests-integration/multiowner/*.test.ts"
test-list = "scarb --profile release build && yarn tsc && yarn mocha --dry-run tests-integration/*.test.ts"
start-devnet = "docker build -t devnet . && docker run -d -p 127.0.0.1:5050:5050 devnet"
kill-devnet = "docker ps -q --filter 'ancestor=devnet' | xargs docker stop"
profile = "scarb --profile release build && node --loader ts-node/esm scripts/profile-account.ts"
deploy-account = "scarb --profile release build && node --loader ts-node/esm scripts/deploy-account.ts"
deploy-multisig = "scarb --profile release build && node --loader ts-node/esm scripts/deploy-multisig.ts"
generate-signature = "node --loader ts-node/esm ./scripts/generate-signature.ts"
update-webauthn-dapp = "scarb --profile release build && cp target/release/*_ArgentAccount* examples/webauthn/src/lib && scarb run format"

# Allows to use the repository as dependency in other projects
[lib]
