[package]
name = "argent_contracts"
version = "0.1.0"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest

[[target.starknet-contract]]
sierra = true
casm = true
allowed-libfuncs-list.name = "audited"

[dependencies]
starknet = "=2.0.0"

[scripts]
format = "scarb fmt && yarn format"
lint = "yarn lint"
start-devnet = "INSTALLATION_FOLDER_CARGO=./cairo/Cargo.toml ./scripts/start-devnet.sh"
integration-tests = "yarn test:ci"
profile = "yarn profile"
