name: Cairo CI

on: push

env:
  SCARB_VERSION: 0.5.0


jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: ${{ env.SCARB_VERSION }}
      - run: scarb fmt --check
      - run: scarb test

  contract-approvers:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Check out main branch
        uses: actions/checkout@v3

      - name: Step 2 - Install project
        run: yarn install --frozen-lockfile

      - name: Step 3 - Check approvers count
        run: yarn ts-node ./scripts/check-contract-approvers.ts 3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
