name: Cairo CI

env:
  ARCHIVE_LINK: https://github.com/starkware-libs/cairo/releases/download/v1.0.0/release-x86_64-unknown-linux-musl.tar.gz
  ARCHIVE_NAME: cairo.zip

on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Check out main branch
        uses: actions/checkout@v3

      - name: Step 2 - Downloading binaries
        run: curl -L -o $ARCHIVE_NAME $ARCHIVE_LINK

      - name: Step 3 - Unzipping binaries
        run: tar -xvf $ARCHIVE_NAME

      - name: Step 4 - Make binaries available
        run: echo "./cairo/bin" >> $GITHUB_PATH

      - name: Step 5 - Run all tests
        run: cairo-test --starknet ./contracts

  format:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Check out main branch
        uses: actions/checkout@v3

      - name: STEP
        run: |
          echo GITHUB_REF is $GITHUB_REF
          echo PR_NUMBER is $PR_NUMBER
          echo event number is ${{ github.event.number }}
          echo "::set-output name=pull_request_number::$(gh pr view --json number -q .number || echo "")"
          echo pull_request_number ${{ steps.pr.outputs.pull_request_number }}
          echo octokit
          yarn ts-node scripts/contract-approvals.ts
          echo octokit end
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.number }}

      - name: Step 2 - Downloading binaries
        run: curl -L -o $ARCHIVE_NAME $ARCHIVE_LINK

      - name: Step 3 - Unzipping binaries
        run: tar -xvf $ARCHIVE_NAME

      - name: Step 4 - Make binaries available
        run: echo "./cairo/bin" >> $GITHUB_PATH

      - name: Step 5 - Check formatting
        run: cairo-format --check --recursive ./contracts
