name: Cairo CI

on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Scarb
        id: get-scarb-version
        run:
          echo "::set-output name=SCARB_VERSION::$(awk '{print $2}' .tool-versions)"
      - uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: ${{ steps.get-scarb-version.outputs.SCARB_VERSION }}
      - run: scarb test
  
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Scarb
        id: get-scarb-version
        run:
          echo "::set-output name=SCARB_VERSION::$(awk '{print $2}' .tool-versions)"
      - uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: ${{ steps.get-scarb-version.outputs.SCARB_VERSION }}
      - run: scarb fmt --check

  contract-approvers:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Check out main branch
        uses: actions/checkout@v3

      - name: Step 2 - Install project
        run: yarn install --frozen-lockfile

      - name: Step 3 - Check approvers count
        run: yarn ts-node ./scripts/check-contract-approvers.ts 3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
