name: Cairo CI

on: push

jobs:
  tests:
        strategy:

      fail-fast: true # In case one of the jobs fails, the other jobs will be cancelled

      matrix:

        runs-on: [ buildjet-2vcpu-ubuntu-2204, buildjet-4vcpu-ubuntu-2204, buildjet-8vcpu-ubuntu-2204, buildjet-16vcpu-ubuntu-2204 ]

    name: Test - ${{matrix.runs-on}}

    runs-on: ${{matrix.runs-on}}
    steps:
      - name: Step 1 - Check out main branch
        uses: actions/checkout@v3
      - name: Step 2 - Getting scarb
        uses: software-mansion/setup-scarb@v1.3.2
      - name: Step 3 - Testing
        run: scarb test
  
  format:
        strategy:

      fail-fast: true # In case one of the jobs fails, the other jobs will be cancelled

      matrix:

        runs-on: [ buildjet-2vcpu-ubuntu-2204, buildjet-4vcpu-ubuntu-2204, buildjet-8vcpu-ubuntu-2204, buildjet-16vcpu-ubuntu-2204 ]

    name: Test - ${{matrix.runs-on}}

    runs-on: ${{matrix.runs-on}}
    steps:
      - name: Step 1 - Check out main branch
        uses: actions/checkout@v3
      - name: Step 2 - Getting scarb
        uses: software-mansion/setup-scarb@v1.3.2
      - name: Step 3 - Checking format
        run: scarb fmt --check
