name: Rust CI

on:
  push:
    branches: 
      - develop
      - main
  pull_request: 
    branches: 
      - develop
      - main[develop, main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2022-11-03
      - name: Set up cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install cairo
        run: make install-cairo
      - name: Run all tests
        run: make test
      - name: Check formatting
        run: make check-format
