name: Rust CI

on:
  push:
    branches: 
      - develop
      - main
  pull_request: 
    branches: 
      - develop
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Check out main branch
        uses: actions/checkout@v3
      - name: Step 2 - Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Step 3 - Set up cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            cairo/
          key: cargo
      - name: Step 4 - Install/Update cairo
        run: make install-cairo
      - name: Step 5 - Run all tests
        run: make test
      - name: Step 6 - Check formatting
        run: make check-format
