name: Integration CI

on: push

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out main branch
        uses: actions/checkout@v3

      - name: Setup Scarb
        id: get-scarb-version
        run:
          echo "::set-output name=SCARB_VERSION::$(awk '{print $2}' .tool-versions)"
      - uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: ${{ steps.get-scarb-version.outputs.SCARB_VERSION }}
          
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip"

      - name: Install python requirements
        run: pip3 install -r requirements.txt

      - name: Install cairo for devnet
        run: make install-devnet-cairo

      - name: Install project
        run: yarn install --frozen-lockfile

      - name: Start devnet in background
        run: |
          scarb run start-devnet &
          ./scripts/wait-devnet-ready.sh

      - name: Run integration tests
        run: scarb run integration-tests

  format:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Check out main branch
        uses: actions/checkout@v3

      - name: Step 2 - Install project
        run: yarn install --frozen-lockfile

      - name: Step 3 - Check correct formatting
        run: yarn format:check

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Check out main branch
        uses: actions/checkout@v3

      - name: Step 2 - Install project
        run: yarn install --frozen-lockfile

      - name: Step 3 - Check correct linting
        run: yarn lint:check
