name: Integration CI

on: push

jobs:
  integration-tests:
        strategy:

      fail-fast: true # In case one of the jobs fails, the other jobs will be cancelled

      matrix:

        runs-on: [ buildjet-2vcpu-ubuntu-2204, buildjet-4vcpu-ubuntu-2204, buildjet-8vcpu-ubuntu-2204, buildjet-16vcpu-ubuntu-2204, buildjet-32vcpu-ubuntu-2204 ]

    name: Test - ${{matrix.runs-on}}

    runs-on: ${{matrix.runs-on}}
    steps:
      - name: Check out main branch
        uses: actions/checkout@v3

      - name: Setup Scarb
        uses: software-mansion/setup-scarb@v1.3.2
          
      - name: Install project
        run: yarn install --frozen-lockfile

      - name: Start devnet in background
        run: |
          scarb run start-devnet &
          ./scripts/wait-devnet-ready.sh

      - name: Run integration tests
        run: scarb --release build && tsc && yarn mocha tests-integration/*.test.ts --forbid-only --forbid-pending

  gas-report:
        strategy:

      fail-fast: true # In case one of the jobs fails, the other jobs will be cancelled

      matrix:

        runs-on: [ buildjet-2vcpu-ubuntu-2204, buildjet-4vcpu-ubuntu-2204, buildjet-8vcpu-ubuntu-2204, buildjet-16vcpu-ubuntu-2204,  buildjet-32vcpu-ubuntu-2204]

    name: Test - ${{matrix.runs-on}}

    runs-on: ${{matrix.runs-on}}
    steps:
      - name: Check out main branch
        uses: actions/checkout@v3

      - name: Setup Scarb
        uses: software-mansion/setup-scarb@v1.3.2
          
      - name: Install project
        run: yarn install --frozen-lockfile

      - name: Start devnet in background
        run: |
          scarb run start-devnet &
          ./scripts/wait-devnet-ready.sh

      - name: Gas report
        run: scarb run profile --check

  format:
        strategy:

      fail-fast: true # In case one of the jobs fails, the other jobs will be cancelled

      matrix:

        runs-on: [ buildjet-2vcpu-ubuntu-2204, buildjet-4vcpu-ubuntu-2204, buildjet-8vcpu-ubuntu-2204, buildjet-16vcpu-ubuntu-2204,  buildjet-32vcpu-ubuntu-2204]

    name: Test - ${{matrix.runs-on}}

    runs-on: ${{matrix.runs-on}}
    steps:
      - name: Step 1 - Check out main branch
        uses: actions/checkout@v3

      - name: Step 2 - Install project
        run: yarn install --frozen-lockfile

      - name: Step 3 - Check correct formatting
        run: yarn prettier --check .

  lint:
        strategy:

      fail-fast: true # In case one of the jobs fails, the other jobs will be cancelled

      matrix:

        runs-on: [ buildjet-2vcpu-ubuntu-2204, buildjet-4vcpu-ubuntu-2204, buildjet-8vcpu-ubuntu-2204, buildjet-16vcpu-ubuntu-2204, buildjet-32vcpu-ubuntu-2204]

    name: Test - ${{matrix.runs-on}}

    runs-on: ${{matrix.runs-on}}
    steps:
      - name: Step 1 - Check out main branch
        uses: actions/checkout@v3

      - name: Step 2 - Install project
        run: yarn install --frozen-lockfile

      - name: Step 3 - Check correct linting
        run: yarn eslint .
